databases:
  - name: hisakimuscle-site2_DB
    databaseName: postgres://hisakimuscle_site2_db_user:8KWboc7Ub3AU7Tns5EYPFXWhGQiz1N3I@dpg-cfjnirha6gductjks7cg-a/hisakimuscle_site2_db
    user: hisakimuscle-site2
    region: singapore

services:
  - type: web
    name: hisakimuscle-site2
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hisakimuscle-site2_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false